import { ArrowUpRight, FileText } from 'lucide-react';
import { Link } from 'react-router-dom';
import PageIntro from '../components/PageIntro';
import SectionLabel from '../components/SectionLabel';
import ContactBanner from '../components/ContactBanner';
import { posts, profile } from '../data/portfolio';
export default function ExperiencePage() {
  return <main id="main">
    <PageIntro number="02" label="THE JOURNEY SO FAR" title={<>Learning.<br />Building. <em>Growing.</em></>} description="From Computer Science fundamentals to hands-on mobile development and applied machine learning. Here’s where I’m learning my craft." />
    <section className="timeline-section" data-reveal><SectionLabel number="01">EXPERIENCE</SectionLabel><div className="timeline-entry"><div className="timeline-meta"><span className="status-dot" /><span>AUG 2026 — PRESENT<small>INTERNSHIP · REMOTE</small></span></div><div className="timeline-body"><a className="company-link" href="https://www.linkedin.com/company/big-brainss/" target="_blank" rel="noreferrer">BIG BRAINS <ArrowUpRight size={14} /></a><h2>Flutter Developer<br /><em>& AI/ML Intern.</em></h2><p>Developing responsive, cross-platform applications with Flutter and Dart while gaining practical experience in applied machine learning.</p><ul><li>Building modular interfaces, widget structures, and state-managed mobile experiences.</li><li>Working with connected app flows and backend integration through the Coffee Shop project.</li><li>Exploring an educational early-warning prototype using Python, an existing Logistic Regression model, and Gradio.</li><li>Using Git and GitHub to organize code and iterate on projects.</li></ul><div className="tags">{['Flutter', 'Dart', 'GetX', 'Python', 'scikit-learn', 'Gradio', 'Git'].map(tool => <span key={tool}>{tool}</span>)}</div><Link className="underlined-link" to="/projects">Explore the projects <ArrowUpRight size={16} /></Link></div></div></section>
    <section className="timeline-section" data-reveal><SectionLabel number="02">EDUCATION</SectionLabel><div className="timeline-entry"><div className="timeline-meta"><span className="status-dot" /><span>OCT 2023 — OCT 2027<small>EXPECTED GRADUATION 2027</small></span></div><div className="timeline-body"><span className="eyebrow">UNIVERSITY OF MANAGEMENT AND TECHNOLOGY</span><h2>BS Computer <em>Science.</em></h2><p>UMT · Lahore, Pakistan</p><p>Building a foundation in programming, object-oriented design, data structures and algorithms, and database systems. Applying that learning to mobile, web, and AI projects.</p><div className="tags"><span>Computer Science</span><span>Software development</span><span>AI & deep learning</span></div></div></div><div className="timeline-entry secondary-entry"><div className="timeline-meta"><span className="status-dot" /><span>JAN 2021 — JUN 2023<small>INTERMEDIATE EDUCATION</small></span></div><div className="timeline-body"><span className="eyebrow">PUNJAB GROUP OF COLLEGES</span><h3>ICS · Computer Science</h3><p>The starting point of my formal Computer Science education.</p></div></div></section>
    <section className="section" data-reveal><SectionLabel number="03">NOTES FROM THE JOURNEY</SectionLabel><div className="section-heading"><h2>Building <em>in public.</em></h2><a className="underlined-link" href={`${profile.linkedin}recent-activity/all/`} target="_blank" rel="noreferrer">All posts <ArrowUpRight size={16} /></a></div><div className="posts-grid">{posts.map(post => <a className="post" key={post.url} href={post.url} target="_blank" rel="noreferrer"><span className="eyebrow">{post.label}</span><h3>{post.title}<ArrowUpRight size={19} /></h3><p>{post.description}</p><span className="text-link">Read on LinkedIn <ArrowUpRight size={14} /></span></a>)}</div><div className="cv-banner"><div><span className="eyebrow">THE FULL PICTURE</span><p>Prefer a document? Take my CV with you.</p></div><Link className="pill" to="/cv"><FileText size={16} /> Preview CV</Link></div></section>
    <ContactBanner />
  </main>;
}
