import { ArrowDown, ArrowDownRight, ArrowUpRight, FileText, Github, Linkedin, Mail, Plus } from 'lucide-react';
import { Link } from 'react-router-dom';
import ProjectCard from '../components/ProjectCard';
import SectionLabel from '../components/SectionLabel';
import { disciplines, explorations, posts, profile, projects } from '../data/portfolio';
export default function HomePage() {
  return (      <main id="main">
        <section id="home" className="hero" aria-label="Introduction">
          <div className="hero-top"><span className="eyebrow">DEVELOPER. EXPLORER. ALWAYS A STUDENT.</span><span className="edition eyebrow">PORTFOLIO / 2026</span></div>
          <div className="hero-grid">
            <div className="hero-copy"><div className="intro-kicker"><span className="status-dot" /> MOBILE DEVELOPMENT & APPLIED ML</div><h1>Hello<span className="hello-dot">.</span><span className="sr-only"> I’m Ahsan Qamar, a Flutter developer and Computer Science undergraduate in Lahore.</span></h1><div className="hero-description"><span className="small-star" aria-hidden="true">✳</span><p>I’m <strong>Ahsan Qamar</strong> — building thoughtful mobile experiences and exploring what’s possible with <em>code & curiosity.</em></p></div><div className="hero-cta"><Link className="button-primary" to="/projects">Explore my work <ArrowDownRight size={18} /></Link>{profile.cv ? <Link className="text-link" to="/cv"><FileText size={15} /> Preview CV</Link> : <span className="cv-control"><button className="text-link" disabled title="CV will be available once the PDF is provided"><FileText size={15} /> Download CV</button><span>Coming soon</span></span>}</div></div>
            <div className="portrait-column"><div className="portrait-frame"><img src={profile.portrait} alt="Ahsan Qamar wearing a suit" width="1122" height="1402" fetchPriority="high" /><div className="portrait-caption"><span>AHSAN QAMAR</span><span>DEVELOPER & CURIOUS HUMAN</span></div></div><div className="portrait-side eyebrow">FLUTTER / MACHINE LEARNING / WEB</div></div>
          </div>
          <div className="hero-bottom"><a className="scroll-link eyebrow" href="#about"><ArrowDown size={15} /> SCROLL TO DISCOVER</a><div className="location"><span className="status-dot" /><span>Based in Lahore<small>Pakistan</small></span></div></div>
        </section>

        <section id="about" className="section about-section" data-reveal>
          <SectionLabel number="01">A LITTLE ABOUT ME</SectionLabel>
          <div className="about-grid"><h2>Good software starts<br />with a little <em>curiosity.</em></h2><div className="about-body"><p className="lead">A Computer Science undergraduate at UMT Lahore, a Flutter and AI/ML intern at Big Brains, and someone who likes turning ideas into things you can actually use.</p><p>My work moves between mobile development, machine learning, and the web — from coffee-ordering experiences to CNN experiments and tools that make data easier to understand. I’m also exploring generative AI with Qwen, Stable Diffusion, and FastAPI.</p><Link className="underlined-link" to="/about">More about me <ArrowUpRight size={17} /></Link><dl className="profile-details"><div><dt>CURRENTLY</dt><dd>{profile.role}<br /><span>Big Brains · Remote</span></dd></div><div><dt>EDUCATION</dt><dd>BS Computer Science · UMT<br /><span>Expected graduation: 2027</span></dd></div></dl></div></div>
          <div className="skill-strip"><span className="eyebrow">MY EVERYDAY TOOLKIT</span><div>{['Flutter', 'Dart', 'Python', 'React', 'TensorFlow', 'Node.js', 'MySQL'].map(skill => <span key={skill}>{skill}</span>)}</div></div>
        </section>

        <section id="work" className="section work-section" data-reveal>
          <SectionLabel number="02">BUILT WITH INTENTION</SectionLabel><div className="section-heading"><h2>Selected <em>work.</em></h2><a className="underlined-link" href={profile.github} target="_blank" rel="noreferrer">My GitHub <ArrowUpRight size={17} /></a></div><p className="section-description">Small details. Real problems. A few things I’ve been building.</p>
          <div className="projects-grid">{projects.slice(0, 4).map((project, index) => <ProjectCard key={project.repo} project={project} index={index} />)}</div>
          <Link className="pill more-projects" to="/projects">View all projects <ArrowUpRight size={16} /></Link>
          <div className="explorations"><div><span className="eyebrow">ALSO EXPLORING</span><p>Experiments in AI,<br />and beyond.</p></div><div className="explorations-list">{explorations.map(item => <div key={item.title}><h3>{item.title}</h3><p>{item.detail}</p>{item.link && <a className="text-link exploration-link" href={item.link} target="_blank" rel="noreferrer">View notebook <ArrowUpRight size={13} /></a>}</div>)}<a href={`${profile.github}/Ahsan-Qamar-Dev`} className="text-link" target="_blank" rel="noreferrer">More experiments on my GitHub profile <ArrowUpRight size={15} /></a></div></div>
        </section>

        <section className="section expertise-section" data-reveal><SectionLabel number="03">WHERE I FOCUS</SectionLabel><div className="expertise-grid"><h2>Different tools.<br />One <em>mindset.</em></h2><div className="disciplines">{disciplines.map((item, index) => <details key={item.title}><summary><span className="eyebrow">0{index + 1}</span><span>{item.title}</span><Plus size={20} /></summary><div className="discipline-body"><p>{item.detail}</p><span>{item.tools}</span></div></details>)}</div></div></section>

        <section id="journey" className="section journey-section" data-reveal><SectionLabel number="04">LEARNING BY BUILDING</SectionLabel><div className="journey-grid"><div><h2>A work <em>in progress.</em></h2><p className="section-description">Growing my craft, one project at a time.</p><Link className="underlined-link journey-page-link" to="/experience">My experience <ArrowUpRight size={17} /></Link></div><div className="journey-items"><div><span className="eyebrow">EXPERIENCE / {profile.internshipDates.toUpperCase()}</span><h3>{profile.role}</h3><p>Big Brains · Remote</p><span className="journey-note">Cross-platform mobile apps and applied machine learning</span></div><div><span className="eyebrow">EDUCATION / 2023 — 2027</span><h3>BS Computer Science</h3><p>University of Management and Technology</p><span className="journey-note">Lahore, Pakistan · Expected October 2027</span></div><div><span className="eyebrow">FOUNDATION / 2021 — 2023</span><h3>ICS · Computer Science</h3><p>Punjab Group of Colleges</p></div></div></div><div className="posts-heading"><h3>Building <em>in public.</em></h3><a href={`${profile.linkedin}recent-activity/all/`} className="text-link" target="_blank" rel="noreferrer">All LinkedIn posts <ArrowUpRight size={16} /></a></div><div className="posts-grid">{posts.map(post => <a className="post" key={post.url} href={post.url} target="_blank" rel="noreferrer"><span className="eyebrow">{post.label}</span><h3>{post.title} <ArrowUpRight size={19} /></h3><p>{post.description}</p><span className="text-link">Read the post <ArrowUpRight size={14} /></span></a>)}</div></section>

        <section id="contact" className="contact-section" data-reveal><SectionLabel number="05">NEXT CHAPTER</SectionLabel><div className="contact-grid"><div><h2>Have an idea?<br />Let’s make it <em>real.</em></h2><p>A mobile app, a collaboration, or a conversation about<br className="desktop-break" /> technology — I’d love to hear from you.</p><a href={`mailto:${profile.email}`} className="contact-email">Say hello <ArrowUpRight size={34} /></a></div><div className="contact-links"><span className="eyebrow">FIND ME ELSEWHERE</span><a href={profile.github} target="_blank" rel="noreferrer"><Github size={19} /> GitHub <ArrowUpRight size={17} /></a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={19} /> LinkedIn <ArrowUpRight size={17} /></a><a href={`mailto:${profile.email}`}><Mail size={19} /> <span>{profile.email}</span> <ArrowUpRight size={17} /></a></div></div></section>
      </main>
  );
}

